config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'statics#index'
  resources :statics  do
    collection do
      get   'about_us'
      get   'admissions'
      get   'announcements'
      get   'facilities'
      get   'photo_galleries'
    end
  end
  match '/home',   to: 'statics#index',   via: 'get'
  match '/about_us',   to: 'statics#about_us',   via: 'get'
  match '/mission_vision',   to: 'statics#mission_vision',   via: 'get'
  match '/admissions',   to: 'statics#admissions',   via: 'get'
  match '/announcements',   to: 'statics#announcements',   via: 'get'
  match '/facilities',   to: 'statics#facilities',   via: 'get'
  match '/photo_galleries',   to: 'statics#photo_galleries',   via: 'get'
  match '/admission/:id',   to: 'statics#show',   via: 'get',   as: 'admission'
  match '/announcement/:id',   to: 'statics#show',   via: 'get',   as: 'announcement'
  match '/post/:id',   to: 'statics#show',   via: 'get',   as: 'post'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # 1 = Admission
  # 2 = Announcements
  # 3 = Facilities
  # 4 = Photo Gallery
  # 5 = About Us
  # 6 = Mission Vision
  has_many_attached :image_attachment

  def self.get_choices
   setting = Setting.first
   return [[1, setting.menu_2], [2, setting.menu_3], [3, setting.menu_4], [4, setting.menu_5], [5, setting.menu_7], [6, setting.menu_8]]
  end

  def self.admissions
    Post.where(section_id: 1).where('is_pinned = ? OR is_pinned IS NULL', false).order("created_at DESC")
  end

  def self.pinned_admissions
    Post.where(section_id: 1, is_pinned: true).order("created_at DESC")
  end

  def self.get_display_admissions
    pinned_size = pinned_admissions.size
    show_limit = 5 - pinned_size

    admissions.limit(show_limit)
  end

  def self.announcements
    Post.where(section_id: 2).where('is_pinned = ? OR is_pinned IS NULL', false).order("created_at DESC")
  end

  def self.pinned_announcements
    Post.where(section_id: 2, is_pinned: true).order("created_at DESC")
  end

  def self.get_display_announcements
    pinned_size = pinned_announcements.size
    show_limit = 5 - pinned_size

    announcements.limit(show_limit)
  end

  def self.facilities
    Post.where(section_id: 3).order("created_at DESC")
  end

  def self.photo_galleries
    Post.where(section_id: 4).order("created_at DESC")
  end

  def self.about_us
    Post.where(section_id: 5).last
  end

  def self.mission_vision
    Post.where(section_id: 6).last
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
  has_one_attached :logo_attachment
  has_one_attached :background_attachment
  has_one_attached :image_attachment
  DEFAULTS = {
    "title" => "Passam National School of Excellence",
    "short_title" => "Panaths",
    "description" => "Educating Better Citizens For Tomorrow",
    "menu_1" => "Home",
    "menu_2" => "Admission",
    "menu_3" => "Announcements",
    "menu_4" => "Facilities",
    "menu_5" => "Photo Gallery",
    "menu_6" => "Contact Us",
    "menu_7" => "About Us",
    "menu_8" => "Mission & Vision",
    "address" => "P.O. Box 624, Wewak ESP Papua New Guinea",
    "email_address" => "passamnhs1978@gmail.com",
    "contact_number_1" => "(675) 71778773",
    "contact_number_2" => "(675) 78321611"
  }


  def self.get_settings_value(kval)
    # puts "working...."
    default_settings = Setting.first
    if default_settings
      if default_settings[kval]
          return default_settings[kval]
      end
    end

    return Setting::DEFAULTS[kval]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :get_settings


  def get_settings
    @setting = Setting.first
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index

  end

  def show
    @post = Post.find(params[:id])
    render 'show_post'
  end

  def about_us
    @post = Post.about_us
  end

  def mission_vision
    @post = Post.mission_vision
  end

  def admissions
    @posts = Post.admissions
  end

  def announcements
    @posts = Post.announcements
  end

  def facilities
    @posts = Post.facilities
  end

  def photo_galleries
    @posts = Post.photo_galleries
  end

  def create
    UserMailer.with(name: params[:name], email: params[:email], phone: params[:phone], message: params[:message]).send_contact.deliver_now
    head :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def truncate_html_to_sentence(notes)
    if !notes.nil?
      truncate(ActionView::Base.full_sanitizer.sanitize(notes), length: 50, omission: '...')
    else
      ""
    end
  end

  def truncate_html_length_to_sentence(notes, char_length)
    if !notes.nil?
      truncate(ActionView::Base.full_sanitizer.sanitize(notes), length: char_length, omission: '...')
    else
      ""
    end
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
  def get_title
    get_settings_value('title')
  end
  def get_short_title
    get_settings_value('short_title')
  end

  def get_description
    get_settings_value('description')
  end

  def get_menu_1
    get_settings_value('menu_1')
  end

  def get_menu_2
    get_settings_value('menu_2')
  end

  def get_menu_3
    get_settings_value('menu_3')
  end

  def get_menu_4
    get_settings_value('menu_4')
  end

  def get_menu_5
    get_settings_value('menu_5')
  end

  def get_menu_6
    get_settings_value('menu_6')
  end

  def get_menu_7
    get_settings_value('menu_7')
  end

  def get_menu_8
    get_settings_value('menu_8')
  end

  def get_advisor_message
    get_settings_value('advisor_message')
  end

  def get_section_1
    get_settings_value('section_1')
  end

  def get_section_1_description
    get_settings_value('section_1_description')
  end

  def get_section_2
    get_settings_value('section_2')
  end

  def get_section_2_description
    get_settings_value('section_2_description')
  end

  def get_address
    get_settings_value('address')
  end

  def get_email_address
    get_settings_value('email_address')
  end

  def get_contact_number_1
    get_settings_value('contact_number_1')
  end

  def get_contact_number_2
    get_settings_value('contact_number_2')
  end

  def get_settings_value(kval)
    if default_settings
      if default_settings[kval]
          return default_settings[kval]
      end
    end

    return Setting::DEFAULTS[kval]
  end

  def default_settings
    Setting.first
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title><%= get_title %> | Official Page</title>
    <%= favicon_link_tag 'pnh.png', type: 'image/png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

    <script src="https://use.fontawesome.com/7e41fac1d8.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.3.0/jquery-migrate.min.js" integrity="sha512-WRDB0crT0y8RlW/sPVeMq6+z+UM21gEvrvzXyAcojZEfQt+mGun7+ntGr9HCe3HHuFJspJbb5na4XKBzYCZvaA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha512-U85Jq47KunKegjv6gVMAnQwtQjovdXz/DQOvQoxrD6j3aGfDDbp5AAJuOdnQx1sefM90D9KBKSQkZGR5hrLbtg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.8/holder.min.js" integrity="sha512-O6R6IBONpEcZVYJAmSC+20vdsM07uFuGjFf0n/Zthm8sOFW+lAq/OK1WOL8vk93GBDxtMIy6ocbj6lduyeLuqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script>
        $(document).ready(function () {
            $('.responsive').slick({
                centerMode: true,
                centerPadding: '20px',
                slidesToShow: 1,
                responsive: [
                    {
                        breakpoint: 768,
                        settings: {
                            arrows: false,
                            centerMode: true,
                            centerPadding: '0',
                            slidesToShow: 1
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            arrows: false,
                            centerMode: true,
                            centerPadding: '0',
                            slidesToShow: 1
                        }
                    }
                ]
            });
        });
    </script>
    <style>
        .slick-prev:before {
            color: black;
        }
        .slick-next:before {
            color: black;
        }
    </style>

    <% if !@setting.background_attachment.nil? %>
      <% if @setting.background_attachment.attached? %>
        <style>
            header.masthead {
                background-image: linear-gradient(to top, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url('<%= rails_blob_url(@setting.background_attachment) %>');
            }
        </style>
      <% else %>
        <style>
            header.masthead {
                background: linear-gradient(to top, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7))
            }
        </style>
      <% end %>
    <% else %>
      <style>
          header.masthead {
              background: linear-gradient(to top, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7))
          }
      </style>
    <% end %>

  </head>

  <body id="page-top">
    <%= render "layouts/static/navbar" %>
    <%= yield %>
    <%= render "layouts/static/footer" %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/statics/_admissions.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase"><%= get_menu_2 %></h2>
        <h3 class="section-subheading text-muted"></h3>
      </div>
    </div>
    <div class="row text-center">
      <% Post.pinned_admissions.limit(3).each do |post| %>
        <div class="col-md-4">
          <% if !post.image_attachment.nil? %>
              <% if post.image_attachment.attached? %>
                <%= image_tag post.image_attachment[0], :class => 'img-fluid rounded', :style => 'width: 50%;', :alt => post.title %>
              <% end %>
            <% end %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? truncate_html_length_to_sentence(post.description, 150) : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= admission_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
      <% Post.get_display_admissions.each do |post| %>
        <div class="col-md-4">
          <% if !post.image_attachment.nil? %>
              <% if post.image_attachment.attached? %>
                <%= image_tag post.image_attachment[0], :class => 'img-fluid rounded', :style => 'width: 50%;', :alt => post.title %>
              <% end %>
            <% end %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? truncate_html_length_to_sentence(post.description, 150) : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= admission_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
    </div>
    <div class="row mt-3">
      <div class="col-lg-8 mx-auto text-center">
        <a class="btn btn-outline-primary btn-xl text-uppercase js-scroll-trigger" href="<%= admissions_path %>">See more</a>
      </div>
    </div>
  </div>
</section>

app/views/statics/_announcements.html.erb
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase"><%= get_menu_3 %></h2>
        <h3 class="section-subheading text-muted"></h3>
      </div>
    </div>
    <div class="row text-justify">
      <% Post.pinned_announcements.limit(3).each do |post| %>
        <div class="col-md-4 text-center">
          <div class="team-member">
            <% if !post.image_attachment.nil? %>
              <% if post.image_attachment.attached? %>
                <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
              <% end %>
            <% end %>
            <h4 class="service-heading"><%= post.title %></h4>
            <p class="text-muted"><%= post.description.present? ? truncate_html_length_to_sentence(post.description, 150) : '' %></p>
            <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= announcement_path(:id => post.id) %>">Read More</a>
          </div>
        </div>
      <% end %>
      <% Post.get_display_announcements.each do |post| %>
        <div class="col-md-4 text-center">
          <div class="team-member">
            <% if !post.image_attachment.nil? %>
              <% if post.image_attachment.attached? %>
                <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
              <% end %>
            <% end %>
            <h4 class="service-heading"><%= post.title %></h4>
            <p class="text-muted"><%= post.description.present? ? truncate_html_length_to_sentence(post.description, 150) : '' %></p>
            <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= announcement_path(:id => post.id) %>">Read More</a>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <a class="btn btn-outline-primary btn-xl text-uppercase js-scroll-trigger" href="<%= announcements_path %>">See more</a>
      </div>
    </div>
  </div>
</section>

app/views/statics/_facilities.html.erb
<section class="bg-light" id="facilities">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase"><%= get_menu_4 %></h2>
        <h3 class="section-subheading text-muted"></h3>
      </div>
    </div>
    <div class="row">
      <% Post.facilities.limit(9).each do |post| %>
        <div class="col-md-4 text-center">
          <div class="team-member">
            <% if !post.image_attachment.nil? %>
              <% if post.image_attachment.attached? %>
                <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
              <% end %>
            <% end %>
            <h4 class="service-heading"><%= post.title %></h4>
            <p class="text-muted"><%= post.description.present? ? truncate_html_length_to_sentence(post.description, 150) : '' %></p>
            <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= post_path(:id => post.id) %>">Read More</a>
          </div>
        </div>
      <% end %>
    </div>
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <a class="btn btn-outline-primary btn-xl text-uppercase js-scroll-trigger" href="<%= facilities_path %>">See more</a>
        </div>
    </div>
  </div>
</section>

app/views/statics/_image_carousel.html.erb
<% image_size ||= 400 %>

<% if !post.image_attachment.nil?  %>
  <% if post.image_attachment.attached? %>
    <div class='text-center' style='max-width: <%= image_size %>px; margin: auto;'>
      <div class="responsive">
        <% post.image_attachment.each do |image_attachment| %>
          <div class="">
            <%= image_tag image_attachment, :class => 'img-fluid mx-auto rounded', :style => 'width: 100%; max-width: 350px;', :alt => post.title %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/statics/_photo_gallery.html.erb
<section class="bg-light" id="team">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase"><%= get_menu_5 %></h2>
        <h3 class="section-subheading text-muted"></h3>
      </div>
    </div>
    <div class="row">
      <% Post.photo_galleries.limit(9).each do |post| %>
        <div class="col-md-4 text-center">
          <div class="team-member">
            <% if !post.image_attachment.nil? %>
              <% if post.image_attachment.attached? %>
                <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :style => 'width: 100%; max-width: 250px;', :alt => post.title %>
              <% end %>
            <% end %>
            <h4 class="service-heading"><%= post.title %></h4>
            <p class="text-muted"><%= post.description.present? ? truncate_html_length_to_sentence(post.description, 150) : '' %></p>
            <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= post_path(:id => post.id) %>">Read More</a>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <a class="btn btn-outline-primary btn-xl text-uppercase js-scroll-trigger" href="<%= photo_galleries_path %>">See more</a>
      </div>
    </div>
  </div>
</section>

app/views/statics/about_us.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading text-uppercase"><%= get_menu_7 %></div>
      <div class="intro-lead-in" style="font-size: 2em;"><%= get_title %></div>
    </div>
  </div>
</header>

<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row text-justify">
      <div class="col-md-12 text-center">
        <div class="team-member">
          <%= render partial: 'image_carousel', locals: { post: @post, image_size: 600 } %>
          <p class="text-muted"><%= @post.description.present? ? @post.description.html_safe : '' %></p>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- Contact -->
<%= render 'contact_us' %>

app/views/statics/admissions.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading text-uppercase"><%= get_menu_2 %></div>
      <div class="intro-lead-in" style="font-size: 2em;"><%= get_title %></div>
    </div>
  </div>
</header>

<section id="services">
  <div class="container">
    <div class="row text-center">
      <% Post.pinned_admissions.each do |post| %>
        <div class="col-md-12  my-3">
          <% if !post.image_attachment.nil? %>
            <% if post.image_attachment.attached? %>
              <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
            <% end %>
          <% end %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 1000)}".html_safe : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= admission_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
      <% @posts.limit(20).each do |post| %>
        <div class="col-md-12  my-3">
          <% if !post.image_attachment.nil? %>
            <% if post.image_attachment.attached? %>
              <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
            <% end %>
          <% end %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 1000)}".html_safe : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= admission_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
    </div>
  </div>
</section>

<!-- Contact -->
<%= render 'contact_us' %>

app/views/statics/announcements.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading text-uppercase"><%= get_menu_3 %></div>
      <div class="intro-lead-in" style="font-size: 2em;"><%= get_title %></div>
    </div>
  </div>
</header>

<section id="services">
  <div class="container">
    <div class="row text-center">
      <% Post.pinned_announcements.each do |post| %>
        <div class="col-md-12 my-3">
          <% if !post.image_attachment.nil? %>
            <% if post.image_attachment.attached? %>
              <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
            <% end %>
          <% end %>
          <%= render partial: 'image_carousel', locals: { post: post, image_size: 600 } %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 1000)}".html_safe : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= announcement_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
      <% @posts.limit(20).each do |post| %>
        <div class="col-md-12 my-3">
          <% if !post.image_attachment.nil? %>
            <% if post.image_attachment.attached? %>
              <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
            <% end %>
          <% end %>
          <%= render partial: 'image_carousel', locals: { post: post, image_size: 600 } %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 1000)}".html_safe : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= announcement_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
    </div>
  </div>
</section>

<!-- Contact -->
<%= render 'contact_us' %>

app/views/statics/facilities.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading text-uppercase"><%= get_menu_4 %></div>
      <div class="intro-lead-in" style="font-size: 2em;"><%= get_title %></div>
    </div>
  </div>
</header>

<section id="services">
  <div class="container">
    <div class="row text-center">
      <% @posts.limit(20).each do |post| %>
        <div class="col-md-12">
          <% if !post.image_attachment.nil? %>
            <% if post.image_attachment.attached? %>
              <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :alt => post.title %>
            <% end %>
          <% end %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 1000)}".html_safe : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= post_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
    </div>
  </div>
</section>

<!-- Contact -->
<%= render 'contact_us' %>

app/views/statics/index.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading text-uppercase"><%= get_title %></div>
      <div class="intro-lead-in" style="font-size: 2em;"><%= get_description %></div>
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="<%= about_us_path %>">Tell Me More</a>
    </div>
  </div>
</header>

<!-- Admissions -->
<%= render 'admissions' %>


<!-- Announcements -->
<%= render 'announcements' %>


<!-- Facilities -->
<%#= render 'facilities' %>


<!-- Photo Gallery -->
<%= render 'photo_gallery' %>


<!-- Contact -->
<%= render 'contact_us' %>


app/views/statics/photo_galleries.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading text-uppercase"><%= get_menu_5 %></div>
      <div class="intro-lead-in" style="font-size: 2em;"><%= get_title %></div>
    </div>
  </div>
</header>

<section id="services">
  <div class="container">
    <div class="row text-center">
      <% @posts.limit(20).each do |post| %>
        <div class="col-md-12">
          <% if !post.image_attachment.nil? %>
            <% if post.image_attachment.attached? %>
              <%= image_tag post.image_attachment[0], :class => 'mx-auto rounded-circle', :style => 'width: 100%; max-width: 250px;', :alt => post.title %>
            <% end %>
          <% end %>
          <h4 class="service-heading"><%= post.title %></h4>
          <p class="text-muted"><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 1000)}".html_safe : '' %></p>
          <a class="btn btn-primary text-uppercase js-scroll-trigger" href="<%= post_path(:id => post.id) %>">Read More</a>
        </div>
      <% end %>
    </div>
  </div>
</section>

<!-- Contact -->
<%= render 'contact_us' %>